# Generated by Django 4.2.2 on 2023-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_id', models.CharField(max_length=5, null=True)),
                ('article', models.CharField(max_length=255)),
                ('article_clean', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=5, null=True)),
                ('stock_status', models.CharField(max_length=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Manufacturer name')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Mark name')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_id', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Model name')),
            ],
        ),
    ]
