# Generated by Django 4.2.2 on 2023-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_marksmodels_delete_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='manufacturer_id',
            field=models.IntegerField(null=True),
        ),
    ]
