# Generated by Django 4.2.2 on 2023-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_articles_manufacturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price_poland',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
