# Generated by Django 4.2.2 on 2023-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_articles_price_poland'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
