# Generated by Django 4.2.2 on 2023-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price_poland',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
