# Generated by Django 4.2.2 on 2023-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_articles_price_alter_articles_price_poland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='stock_status',
            field=models.IntegerField(default=0),
        ),
    ]
