# Generated by Django 4.2.2 on 2023-06-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_articles_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='manufacturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.manufacturer'),
        ),
    ]
