# Generated by Django 4.2.2 on 2023-06-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_articles_manufacturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
