# Generated by Django 4.2.2 on 2023-06-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_articles_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
