# Generated by Django 4.2.2 on 2023-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_rename_manufacturer_id_articles_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price_poland',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='stock_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
