# Generated by Django 4.2.2 on 2023-06-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_alter_articles_price_alter_articles_price_poland_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_to_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.CharField(max_length=10)),
                ('year_to', models.CharField(max_length=10)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.articles')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.marksmodels')),
            ],
        ),
    ]
