# Generated by Django 4.2.2 on 2023-06-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_cars_to_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.articles')),
            ],
        ),
    ]
