# Generated by Django 4.2.2 on 2023-06-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_articles_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
